// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcBaiduid = "tc_baiduid"

// TcBaiduid mapped from table <tc_baiduid>
type TcBaiduid struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID      int32  `gorm:"column:uid;not null" json:"uid"`
	Bduss    string `gorm:"column:bduss;not null" json:"bduss,omitempty"`
	Stoken   string `gorm:"column:stoken;not null" json:"stoken,omitempty"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Portrait string `gorm:"column:portrait;not null" json:"portrait"`
}

// TableName TcBaiduid's table name
func (*TcBaiduid) TableName() string {
	return TableNameTcBaiduid
}
