// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcKdGrowth = "tc_kd_growth"

// TcKdGrowth mapped from table <tc_kd_growth>
type TcKdGrowth struct {
	ID     int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;uniqueIndex:tc_kd_growth_id_uid_pid,priority:1;index:tc_kd_growth_date_id,priority:2" json:"id"`
	UID    int64  `gorm:"column:uid;type:bigint;not null;uniqueIndex:tc_kd_growth_id_uid_pid,priority:2;index:tc_kd_growth_uid,priority:1" json:"uid"`
	Pid    int64  `gorm:"column:pid;type:bigint;not null;uniqueIndex:tc_kd_growth_id_uid_pid,priority:3;index:tc_kd_growth_pid,priority:1" json:"pid"`
	Status string `gorm:"column:status;type:text" json:"status"`
	Log    string `gorm:"column:log;type:text" json:"log"`
	Date   int32  `gorm:"column:date;type:int;not null;index:tc_kd_growth_date_id,priority:1" json:"date"`
}

// TableName TcKdGrowth's table name
func (*TcKdGrowth) TableName() string {
	return TableNameTcKdGrowth
}
