// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcKdWenkuTask = "tc_kd_wenku_tasks"

// TcKdWenkuTask mapped from table <tc_kd_wenku_tasks>
type TcKdWenkuTask struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID    int64  `gorm:"column:uid;not null" json:"uid"`
	Pid    int64  `gorm:"column:pid;not null" json:"pid"`
	Status string `gorm:"column:status" json:"status"`
	Log    string `gorm:"column:log" json:"log"`
	Date   int32  `gorm:"column:date;not null;default:0" json:"date"`
}

// TableName TcKdWenkuTask's table name
func (*TcKdWenkuTask) TableName() string {
	return TableNameTcKdWenkuTask
}
