// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcKdRenewManager = "tc_kd_renew_manager"

// TcKdRenewManager mapped from table <tc_kd_renew_manager>
type TcKdRenewManager struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID    int32  `gorm:"column:uid;not null" json:"uid"`
	Pid    int32  `gorm:"column:pid;not null" json:"pid"`
	Fname  string `gorm:"column:fname;not null" json:"fname"`
	Fid    int32  `gorm:"column:fid;not null" json:"fid"`
	Tid    string `gorm:"column:tid;not null" json:"tid"`
	Status string `gorm:"column:status;not null" json:"status"`
	Date   int32  `gorm:"column:date;not null" json:"date"`
	End    int32  `gorm:"column:end;not null" json:"end"`
	Log    string `gorm:"column:log;not null" json:"log"`
}

// TableName TcKdRenewManager's table name
func (*TcKdRenewManager) TableName() string {
	return TableNameTcKdRenewManager
}
