// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcKdForumLike = "tc_kd_forum_like"

// TcKdForumLike mapped from table <tc_kd_forum_like>
type TcKdForumLike struct {
	ID        int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;index:tc_kd_forum_like_status_date_id,priority:3" json:"id"`
	UID       int32  `gorm:"column:uid;type:int;not null" json:"uid"`
	Pid       int32  `gorm:"column:pid;type:int;not null;uniqueIndex:tc_kd_forum_like_pid_fname,priority:1;index:tc_kd_forum_like_pid_date,priority:1" json:"pid"`
	Fid       int32  `gorm:"column:fid;type:int" json:"fid"`
	Fname     string `gorm:"column:fname;type:varchar(63);not null;uniqueIndex:tc_kd_forum_like_pid_fname,priority:2;index:tc_kd_forum_like_fname_date,priority:1" json:"fname"`
	Status    int32  `gorm:"column:status;type:int;index:tc_kd_forum_like_status_date_id,priority:1" json:"status"`
	LastError string `gorm:"column:last_error;type:text" json:"last_error"`
	Date      int64  `gorm:"column:date;type:int;not null;index:tc_kd_forum_like_status_date_id,priority:2;index:tc_kd_forum_like_pid_date,priority:2;index:tc_kd_forum_like_fname_date,priority:2" json:"date"`
	Date2     int64  `gorm:"column:date2;type:int;not null" json:"-"`
}

// TableName TcKdForumLike's table name
func (*TcKdForumLike) TableName() string {
	return TableNameTcKdForumLike
}
