// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcOption = "tc_options"

// TcOption mapped from table <tc_options>
type TcOption struct {
	Name  string `gorm:"column:name;type:varchar(124);primaryKey" json:"name"`
	Value string `gorm:"column:value;type:text;not null" json:"value"`
}

// TableName TcOption's table name
func (*TcOption) TableName() string {
	return TableNameTcOption
}
