// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcPlugin = "tc_plugins"

// TcPlugin mapped from table <tc_plugins>
type TcPlugin struct {
	Name    string `gorm:"column:name;type:varchar(50);primaryKey" json:"name"`
	Status  int    `gorm:"column:status;type:int;not null" json:"status"`
	Ver     string `gorm:"column:ver;type:varchar(15);not null" json:"ver"`
	Options string `gorm:"column:options;type:text" json:"options"`
}

// TableName TcPlugin's table name
func (*TcPlugin) TableName() string {
	return TableNameTcPlugin
}
