// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcTieba = "tc_tieba"

// TcTieba mapped from table <tc_tieba>
type TcTieba struct {
	ID        int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UID       int32  `gorm:"column:uid;type:int;not null;uniqueIndex:tc_tieba_uid_pid_fid,priority:1" json:"uid"`
	Pid       int32  `gorm:"column:pid;type:int;not null;uniqueIndex:tc_tieba_uid_pid_fid,priority:2;index:tc_tieba_pid,priority:1" json:"pid"`
	Fid       int32  `gorm:"column:fid;type:int;not null;uniqueIndex:tc_tieba_uid_pid_fid,priority:3;index:tc_tieba_tieba_fid,priority:2" json:"fid"`
	Tieba     string `gorm:"column:tieba;type:varchar(200);not null;index:tc_tieba_tieba_fid,priority:1" json:"tieba"`
	No        int    `gorm:"column:no;type:int;not null" json:"no"`
	Status    int32  `gorm:"column:status;type:int;not null" json:"status"`
	Latest    int32  `gorm:"column:latest;type:int;not null" json:"latest"`
	LastError string `gorm:"column:last_error;type:text" json:"last_error"`
}

// TableName TcTieba's table name
func (*TcTieba) TableName() string {
	return TableNameTcTieba
}
