// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/BANKA2017/tbsign_go/dao/model"
)

func newTcKdGrowth(db *gorm.DB, opts ...gen.DOOption) tcKdGrowth {
	_tcKdGrowth := tcKdGrowth{}

	_tcKdGrowth.tcKdGrowthDo.UseDB(db, opts...)
	_tcKdGrowth.tcKdGrowthDo.UseModel(&model.TcKdGrowth{})

	tableName := _tcKdGrowth.tcKdGrowthDo.TableName()
	_tcKdGrowth.ALL = field.NewAsterisk(tableName)
	_tcKdGrowth.ID = field.NewInt64(tableName, "id")
	_tcKdGrowth.UID = field.NewInt64(tableName, "uid")
	_tcKdGrowth.Pid = field.NewInt64(tableName, "pid")
	_tcKdGrowth.Status = field.NewString(tableName, "status")
	_tcKdGrowth.Log = field.NewString(tableName, "log")
	_tcKdGrowth.Date = field.NewInt32(tableName, "date")

	_tcKdGrowth.fillFieldMap()

	return _tcKdGrowth
}

type tcKdGrowth struct {
	tcKdGrowthDo tcKdGrowthDo

	ALL    field.Asterisk
	ID     field.Int64
	UID    field.Int64
	Pid    field.Int64
	Status field.String
	Log    field.String
	Date   field.Int32

	fieldMap map[string]field.Expr
}

func (t tcKdGrowth) Table(newTableName string) *tcKdGrowth {
	t.tcKdGrowthDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tcKdGrowth) As(alias string) *tcKdGrowth {
	t.tcKdGrowthDo.DO = *(t.tcKdGrowthDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tcKdGrowth) updateTableName(table string) *tcKdGrowth {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.UID = field.NewInt64(table, "uid")
	t.Pid = field.NewInt64(table, "pid")
	t.Status = field.NewString(table, "status")
	t.Log = field.NewString(table, "log")
	t.Date = field.NewInt32(table, "date")

	t.fillFieldMap()

	return t
}

func (t *tcKdGrowth) WithContext(ctx context.Context) *tcKdGrowthDo {
	return t.tcKdGrowthDo.WithContext(ctx)
}

func (t tcKdGrowth) TableName() string { return t.tcKdGrowthDo.TableName() }

func (t tcKdGrowth) Alias() string { return t.tcKdGrowthDo.Alias() }

func (t tcKdGrowth) Columns(cols ...field.Expr) gen.Columns { return t.tcKdGrowthDo.Columns(cols...) }

func (t *tcKdGrowth) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tcKdGrowth) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.ID
	t.fieldMap["uid"] = t.UID
	t.fieldMap["pid"] = t.Pid
	t.fieldMap["status"] = t.Status
	t.fieldMap["log"] = t.Log
	t.fieldMap["date"] = t.Date
}

func (t tcKdGrowth) clone(db *gorm.DB) tcKdGrowth {
	t.tcKdGrowthDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tcKdGrowth) replaceDB(db *gorm.DB) tcKdGrowth {
	t.tcKdGrowthDo.ReplaceDB(db)
	return t
}

type tcKdGrowthDo struct{ gen.DO }

func (t tcKdGrowthDo) Debug() *tcKdGrowthDo {
	return t.withDO(t.DO.Debug())
}

func (t tcKdGrowthDo) WithContext(ctx context.Context) *tcKdGrowthDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tcKdGrowthDo) ReadDB() *tcKdGrowthDo {
	return t.Clauses(dbresolver.Read)
}

func (t tcKdGrowthDo) WriteDB() *tcKdGrowthDo {
	return t.Clauses(dbresolver.Write)
}

func (t tcKdGrowthDo) Session(config *gorm.Session) *tcKdGrowthDo {
	return t.withDO(t.DO.Session(config))
}

func (t tcKdGrowthDo) Clauses(conds ...clause.Expression) *tcKdGrowthDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tcKdGrowthDo) Returning(value interface{}, columns ...string) *tcKdGrowthDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tcKdGrowthDo) Not(conds ...gen.Condition) *tcKdGrowthDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tcKdGrowthDo) Or(conds ...gen.Condition) *tcKdGrowthDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tcKdGrowthDo) Select(conds ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tcKdGrowthDo) Where(conds ...gen.Condition) *tcKdGrowthDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tcKdGrowthDo) Order(conds ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tcKdGrowthDo) Distinct(cols ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tcKdGrowthDo) Omit(cols ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tcKdGrowthDo) Join(table schema.Tabler, on ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tcKdGrowthDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tcKdGrowthDo) RightJoin(table schema.Tabler, on ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tcKdGrowthDo) Group(cols ...field.Expr) *tcKdGrowthDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tcKdGrowthDo) Having(conds ...gen.Condition) *tcKdGrowthDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tcKdGrowthDo) Limit(limit int) *tcKdGrowthDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tcKdGrowthDo) Offset(offset int) *tcKdGrowthDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tcKdGrowthDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tcKdGrowthDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tcKdGrowthDo) Unscoped() *tcKdGrowthDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tcKdGrowthDo) Create(values ...*model.TcKdGrowth) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tcKdGrowthDo) CreateInBatches(values []*model.TcKdGrowth, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tcKdGrowthDo) Save(values ...*model.TcKdGrowth) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tcKdGrowthDo) First() (*model.TcKdGrowth, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcKdGrowth), nil
	}
}

func (t tcKdGrowthDo) Take() (*model.TcKdGrowth, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcKdGrowth), nil
	}
}

func (t tcKdGrowthDo) Last() (*model.TcKdGrowth, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcKdGrowth), nil
	}
}

func (t tcKdGrowthDo) Find() ([]*model.TcKdGrowth, error) {
	result, err := t.DO.Find()
	return result.([]*model.TcKdGrowth), err
}

func (t tcKdGrowthDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TcKdGrowth, err error) {
	buf := make([]*model.TcKdGrowth, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tcKdGrowthDo) FindInBatches(result *[]*model.TcKdGrowth, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tcKdGrowthDo) Attrs(attrs ...field.AssignExpr) *tcKdGrowthDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tcKdGrowthDo) Assign(attrs ...field.AssignExpr) *tcKdGrowthDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tcKdGrowthDo) Joins(fields ...field.RelationField) *tcKdGrowthDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tcKdGrowthDo) Preload(fields ...field.RelationField) *tcKdGrowthDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tcKdGrowthDo) FirstOrInit() (*model.TcKdGrowth, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcKdGrowth), nil
	}
}

func (t tcKdGrowthDo) FirstOrCreate() (*model.TcKdGrowth, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcKdGrowth), nil
	}
}

func (t tcKdGrowthDo) FindByPage(offset int, limit int) (result []*model.TcKdGrowth, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tcKdGrowthDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tcKdGrowthDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tcKdGrowthDo) Delete(models ...*model.TcKdGrowth) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tcKdGrowthDo) withDO(do gen.Dao) *tcKdGrowthDo {
	t.DO = *do.(*gen.DO)
	return t
}
