// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/BANKA2017/tbsign_go/dao/model"
)

func newTcOption(db *gorm.DB, opts ...gen.DOOption) tcOption {
	_tcOption := tcOption{}

	_tcOption.tcOptionDo.UseDB(db, opts...)
	_tcOption.tcOptionDo.UseModel(&model.TcOption{})

	tableName := _tcOption.tcOptionDo.TableName()
	_tcOption.ALL = field.NewAsterisk(tableName)
	_tcOption.Name = field.NewString(tableName, "name")
	_tcOption.Value = field.NewString(tableName, "value")

	_tcOption.fillFieldMap()

	return _tcOption
}

type tcOption struct {
	tcOptionDo tcOptionDo

	ALL   field.Asterisk
	Name  field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (t tcOption) Table(newTableName string) *tcOption {
	t.tcOptionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tcOption) As(alias string) *tcOption {
	t.tcOptionDo.DO = *(t.tcOptionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tcOption) updateTableName(table string) *tcOption {
	t.ALL = field.NewAsterisk(table)
	t.Name = field.NewString(table, "name")
	t.Value = field.NewString(table, "value")

	t.fillFieldMap()

	return t
}

func (t *tcOption) WithContext(ctx context.Context) *tcOptionDo { return t.tcOptionDo.WithContext(ctx) }

func (t tcOption) TableName() string { return t.tcOptionDo.TableName() }

func (t tcOption) Alias() string { return t.tcOptionDo.Alias() }

func (t tcOption) Columns(cols ...field.Expr) gen.Columns { return t.tcOptionDo.Columns(cols...) }

func (t *tcOption) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tcOption) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["name"] = t.Name
	t.fieldMap["value"] = t.Value
}

func (t tcOption) clone(db *gorm.DB) tcOption {
	t.tcOptionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tcOption) replaceDB(db *gorm.DB) tcOption {
	t.tcOptionDo.ReplaceDB(db)
	return t
}

type tcOptionDo struct{ gen.DO }

func (t tcOptionDo) Debug() *tcOptionDo {
	return t.withDO(t.DO.Debug())
}

func (t tcOptionDo) WithContext(ctx context.Context) *tcOptionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tcOptionDo) ReadDB() *tcOptionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tcOptionDo) WriteDB() *tcOptionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tcOptionDo) Session(config *gorm.Session) *tcOptionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tcOptionDo) Clauses(conds ...clause.Expression) *tcOptionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tcOptionDo) Returning(value interface{}, columns ...string) *tcOptionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tcOptionDo) Not(conds ...gen.Condition) *tcOptionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tcOptionDo) Or(conds ...gen.Condition) *tcOptionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tcOptionDo) Select(conds ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tcOptionDo) Where(conds ...gen.Condition) *tcOptionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tcOptionDo) Order(conds ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tcOptionDo) Distinct(cols ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tcOptionDo) Omit(cols ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tcOptionDo) Join(table schema.Tabler, on ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tcOptionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tcOptionDo) RightJoin(table schema.Tabler, on ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tcOptionDo) Group(cols ...field.Expr) *tcOptionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tcOptionDo) Having(conds ...gen.Condition) *tcOptionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tcOptionDo) Limit(limit int) *tcOptionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tcOptionDo) Offset(offset int) *tcOptionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tcOptionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tcOptionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tcOptionDo) Unscoped() *tcOptionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tcOptionDo) Create(values ...*model.TcOption) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tcOptionDo) CreateInBatches(values []*model.TcOption, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tcOptionDo) Save(values ...*model.TcOption) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tcOptionDo) First() (*model.TcOption, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcOption), nil
	}
}

func (t tcOptionDo) Take() (*model.TcOption, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcOption), nil
	}
}

func (t tcOptionDo) Last() (*model.TcOption, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcOption), nil
	}
}

func (t tcOptionDo) Find() ([]*model.TcOption, error) {
	result, err := t.DO.Find()
	return result.([]*model.TcOption), err
}

func (t tcOptionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TcOption, err error) {
	buf := make([]*model.TcOption, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tcOptionDo) FindInBatches(result *[]*model.TcOption, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tcOptionDo) Attrs(attrs ...field.AssignExpr) *tcOptionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tcOptionDo) Assign(attrs ...field.AssignExpr) *tcOptionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tcOptionDo) Joins(fields ...field.RelationField) *tcOptionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tcOptionDo) Preload(fields ...field.RelationField) *tcOptionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tcOptionDo) FirstOrInit() (*model.TcOption, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcOption), nil
	}
}

func (t tcOptionDo) FirstOrCreate() (*model.TcOption, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcOption), nil
	}
}

func (t tcOptionDo) FindByPage(offset int, limit int) (result []*model.TcOption, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tcOptionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tcOptionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tcOptionDo) Delete(models ...*model.TcOption) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tcOptionDo) withDO(do gen.Dao) *tcOptionDo {
	t.DO = *do.(*gen.DO)
	return t
}
