// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/BANKA2017/tbsign_go/dao/model"
)

func newTcUsersOption(db *gorm.DB, opts ...gen.DOOption) tcUsersOption {
	_tcUsersOption := tcUsersOption{}

	_tcUsersOption.tcUsersOptionDo.UseDB(db, opts...)
	_tcUsersOption.tcUsersOptionDo.UseModel(&model.TcUsersOption{})

	tableName := _tcUsersOption.tcUsersOptionDo.TableName()
	_tcUsersOption.ALL = field.NewAsterisk(tableName)
	_tcUsersOption.UID = field.NewInt32(tableName, "uid")
	_tcUsersOption.Name = field.NewString(tableName, "name")
	_tcUsersOption.Value = field.NewString(tableName, "value")

	_tcUsersOption.fillFieldMap()

	return _tcUsersOption
}

type tcUsersOption struct {
	tcUsersOptionDo tcUsersOptionDo

	ALL   field.Asterisk
	UID   field.Int32
	Name  field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (t tcUsersOption) Table(newTableName string) *tcUsersOption {
	t.tcUsersOptionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tcUsersOption) As(alias string) *tcUsersOption {
	t.tcUsersOptionDo.DO = *(t.tcUsersOptionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tcUsersOption) updateTableName(table string) *tcUsersOption {
	t.ALL = field.NewAsterisk(table)
	t.UID = field.NewInt32(table, "uid")
	t.Name = field.NewString(table, "name")
	t.Value = field.NewString(table, "value")

	t.fillFieldMap()

	return t
}

func (t *tcUsersOption) WithContext(ctx context.Context) *tcUsersOptionDo {
	return t.tcUsersOptionDo.WithContext(ctx)
}

func (t tcUsersOption) TableName() string { return t.tcUsersOptionDo.TableName() }

func (t tcUsersOption) Alias() string { return t.tcUsersOptionDo.Alias() }

func (t tcUsersOption) Columns(cols ...field.Expr) gen.Columns {
	return t.tcUsersOptionDo.Columns(cols...)
}

func (t *tcUsersOption) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tcUsersOption) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["uid"] = t.UID
	t.fieldMap["name"] = t.Name
	t.fieldMap["value"] = t.Value
}

func (t tcUsersOption) clone(db *gorm.DB) tcUsersOption {
	t.tcUsersOptionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tcUsersOption) replaceDB(db *gorm.DB) tcUsersOption {
	t.tcUsersOptionDo.ReplaceDB(db)
	return t
}

type tcUsersOptionDo struct{ gen.DO }

func (t tcUsersOptionDo) Debug() *tcUsersOptionDo {
	return t.withDO(t.DO.Debug())
}

func (t tcUsersOptionDo) WithContext(ctx context.Context) *tcUsersOptionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tcUsersOptionDo) ReadDB() *tcUsersOptionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tcUsersOptionDo) WriteDB() *tcUsersOptionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tcUsersOptionDo) Session(config *gorm.Session) *tcUsersOptionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tcUsersOptionDo) Clauses(conds ...clause.Expression) *tcUsersOptionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tcUsersOptionDo) Returning(value interface{}, columns ...string) *tcUsersOptionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tcUsersOptionDo) Not(conds ...gen.Condition) *tcUsersOptionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tcUsersOptionDo) Or(conds ...gen.Condition) *tcUsersOptionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tcUsersOptionDo) Select(conds ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tcUsersOptionDo) Where(conds ...gen.Condition) *tcUsersOptionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tcUsersOptionDo) Order(conds ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tcUsersOptionDo) Distinct(cols ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tcUsersOptionDo) Omit(cols ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tcUsersOptionDo) Join(table schema.Tabler, on ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tcUsersOptionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tcUsersOptionDo) RightJoin(table schema.Tabler, on ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tcUsersOptionDo) Group(cols ...field.Expr) *tcUsersOptionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tcUsersOptionDo) Having(conds ...gen.Condition) *tcUsersOptionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tcUsersOptionDo) Limit(limit int) *tcUsersOptionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tcUsersOptionDo) Offset(offset int) *tcUsersOptionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tcUsersOptionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tcUsersOptionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tcUsersOptionDo) Unscoped() *tcUsersOptionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tcUsersOptionDo) Create(values ...*model.TcUsersOption) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tcUsersOptionDo) CreateInBatches(values []*model.TcUsersOption, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tcUsersOptionDo) Save(values ...*model.TcUsersOption) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tcUsersOptionDo) First() (*model.TcUsersOption, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcUsersOption), nil
	}
}

func (t tcUsersOptionDo) Take() (*model.TcUsersOption, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcUsersOption), nil
	}
}

func (t tcUsersOptionDo) Last() (*model.TcUsersOption, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcUsersOption), nil
	}
}

func (t tcUsersOptionDo) Find() ([]*model.TcUsersOption, error) {
	result, err := t.DO.Find()
	return result.([]*model.TcUsersOption), err
}

func (t tcUsersOptionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TcUsersOption, err error) {
	buf := make([]*model.TcUsersOption, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tcUsersOptionDo) FindInBatches(result *[]*model.TcUsersOption, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tcUsersOptionDo) Attrs(attrs ...field.AssignExpr) *tcUsersOptionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tcUsersOptionDo) Assign(attrs ...field.AssignExpr) *tcUsersOptionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tcUsersOptionDo) Joins(fields ...field.RelationField) *tcUsersOptionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tcUsersOptionDo) Preload(fields ...field.RelationField) *tcUsersOptionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tcUsersOptionDo) FirstOrInit() (*model.TcUsersOption, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcUsersOption), nil
	}
}

func (t tcUsersOptionDo) FirstOrCreate() (*model.TcUsersOption, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcUsersOption), nil
	}
}

func (t tcUsersOptionDo) FindByPage(offset int, limit int) (result []*model.TcUsersOption, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tcUsersOptionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tcUsersOptionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tcUsersOptionDo) Delete(models ...*model.TcUsersOption) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tcUsersOptionDo) withDO(do gen.Dao) *tcUsersOptionDo {
	t.DO = *do.(*gen.DO)
	return t
}
