// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/BANKA2017/tbsign_go/dao/model"
)

func newTcVer4RankList(db *gorm.DB, opts ...gen.DOOption) tcVer4RankList {
	_tcVer4RankList := tcVer4RankList{}

	_tcVer4RankList.tcVer4RankListDo.UseDB(db, opts...)
	_tcVer4RankList.tcVer4RankListDo.UseModel(&model.TcVer4RankList{})

	tableName := _tcVer4RankList.tcVer4RankListDo.TableName()
	_tcVer4RankList.ALL = field.NewAsterisk(tableName)
	_tcVer4RankList.ID = field.NewInt32(tableName, "id")
	_tcVer4RankList.Fid = field.NewInt32(tableName, "fid")
	_tcVer4RankList.Nid = field.NewString(tableName, "nid")
	_tcVer4RankList.Name = field.NewString(tableName, "name")
	_tcVer4RankList.Tieba = field.NewString(tableName, "tieba")
	_tcVer4RankList.Date = field.NewInt32(tableName, "date")

	_tcVer4RankList.fillFieldMap()

	return _tcVer4RankList
}

type tcVer4RankList struct {
	tcVer4RankListDo tcVer4RankListDo

	ALL   field.Asterisk
	ID    field.Int32
	Fid   field.Int32
	Nid   field.String
	Name  field.String
	Tieba field.String
	Date  field.Int32

	fieldMap map[string]field.Expr
}

func (t tcVer4RankList) Table(newTableName string) *tcVer4RankList {
	t.tcVer4RankListDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tcVer4RankList) As(alias string) *tcVer4RankList {
	t.tcVer4RankListDo.DO = *(t.tcVer4RankListDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tcVer4RankList) updateTableName(table string) *tcVer4RankList {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.Fid = field.NewInt32(table, "fid")
	t.Nid = field.NewString(table, "nid")
	t.Name = field.NewString(table, "name")
	t.Tieba = field.NewString(table, "tieba")
	t.Date = field.NewInt32(table, "date")

	t.fillFieldMap()

	return t
}

func (t *tcVer4RankList) WithContext(ctx context.Context) *tcVer4RankListDo {
	return t.tcVer4RankListDo.WithContext(ctx)
}

func (t tcVer4RankList) TableName() string { return t.tcVer4RankListDo.TableName() }

func (t tcVer4RankList) Alias() string { return t.tcVer4RankListDo.Alias() }

func (t tcVer4RankList) Columns(cols ...field.Expr) gen.Columns {
	return t.tcVer4RankListDo.Columns(cols...)
}

func (t *tcVer4RankList) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tcVer4RankList) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.ID
	t.fieldMap["fid"] = t.Fid
	t.fieldMap["nid"] = t.Nid
	t.fieldMap["name"] = t.Name
	t.fieldMap["tieba"] = t.Tieba
	t.fieldMap["date"] = t.Date
}

func (t tcVer4RankList) clone(db *gorm.DB) tcVer4RankList {
	t.tcVer4RankListDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tcVer4RankList) replaceDB(db *gorm.DB) tcVer4RankList {
	t.tcVer4RankListDo.ReplaceDB(db)
	return t
}

type tcVer4RankListDo struct{ gen.DO }

func (t tcVer4RankListDo) Debug() *tcVer4RankListDo {
	return t.withDO(t.DO.Debug())
}

func (t tcVer4RankListDo) WithContext(ctx context.Context) *tcVer4RankListDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tcVer4RankListDo) ReadDB() *tcVer4RankListDo {
	return t.Clauses(dbresolver.Read)
}

func (t tcVer4RankListDo) WriteDB() *tcVer4RankListDo {
	return t.Clauses(dbresolver.Write)
}

func (t tcVer4RankListDo) Session(config *gorm.Session) *tcVer4RankListDo {
	return t.withDO(t.DO.Session(config))
}

func (t tcVer4RankListDo) Clauses(conds ...clause.Expression) *tcVer4RankListDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tcVer4RankListDo) Returning(value interface{}, columns ...string) *tcVer4RankListDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tcVer4RankListDo) Not(conds ...gen.Condition) *tcVer4RankListDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tcVer4RankListDo) Or(conds ...gen.Condition) *tcVer4RankListDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tcVer4RankListDo) Select(conds ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tcVer4RankListDo) Where(conds ...gen.Condition) *tcVer4RankListDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tcVer4RankListDo) Order(conds ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tcVer4RankListDo) Distinct(cols ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tcVer4RankListDo) Omit(cols ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tcVer4RankListDo) Join(table schema.Tabler, on ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tcVer4RankListDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tcVer4RankListDo) RightJoin(table schema.Tabler, on ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tcVer4RankListDo) Group(cols ...field.Expr) *tcVer4RankListDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tcVer4RankListDo) Having(conds ...gen.Condition) *tcVer4RankListDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tcVer4RankListDo) Limit(limit int) *tcVer4RankListDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tcVer4RankListDo) Offset(offset int) *tcVer4RankListDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tcVer4RankListDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tcVer4RankListDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tcVer4RankListDo) Unscoped() *tcVer4RankListDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tcVer4RankListDo) Create(values ...*model.TcVer4RankList) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tcVer4RankListDo) CreateInBatches(values []*model.TcVer4RankList, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tcVer4RankListDo) Save(values ...*model.TcVer4RankList) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tcVer4RankListDo) First() (*model.TcVer4RankList, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4RankList), nil
	}
}

func (t tcVer4RankListDo) Take() (*model.TcVer4RankList, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4RankList), nil
	}
}

func (t tcVer4RankListDo) Last() (*model.TcVer4RankList, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4RankList), nil
	}
}

func (t tcVer4RankListDo) Find() ([]*model.TcVer4RankList, error) {
	result, err := t.DO.Find()
	return result.([]*model.TcVer4RankList), err
}

func (t tcVer4RankListDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TcVer4RankList, err error) {
	buf := make([]*model.TcVer4RankList, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tcVer4RankListDo) FindInBatches(result *[]*model.TcVer4RankList, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tcVer4RankListDo) Attrs(attrs ...field.AssignExpr) *tcVer4RankListDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tcVer4RankListDo) Assign(attrs ...field.AssignExpr) *tcVer4RankListDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tcVer4RankListDo) Joins(fields ...field.RelationField) *tcVer4RankListDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tcVer4RankListDo) Preload(fields ...field.RelationField) *tcVer4RankListDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tcVer4RankListDo) FirstOrInit() (*model.TcVer4RankList, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4RankList), nil
	}
}

func (t tcVer4RankListDo) FirstOrCreate() (*model.TcVer4RankList, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4RankList), nil
	}
}

func (t tcVer4RankListDo) FindByPage(offset int, limit int) (result []*model.TcVer4RankList, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tcVer4RankListDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tcVer4RankListDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tcVer4RankListDo) Delete(models ...*model.TcVer4RankList) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tcVer4RankListDo) withDO(do gen.Dao) *tcVer4RankListDo {
	t.DO = *do.(*gen.DO)
	return t
}
