// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/BANKA2017/tbsign_go/dao/model"
)

func newTcVer4BanUserset(db *gorm.DB, opts ...gen.DOOption) tcVer4BanUserset {
	_tcVer4BanUserset := tcVer4BanUserset{}

	_tcVer4BanUserset.tcVer4BanUsersetDo.UseDB(db, opts...)
	_tcVer4BanUserset.tcVer4BanUsersetDo.UseModel(&model.TcVer4BanUserset{})

	tableName := _tcVer4BanUserset.tcVer4BanUsersetDo.TableName()
	_tcVer4BanUserset.ALL = field.NewAsterisk(tableName)
	_tcVer4BanUserset.ID = field.NewInt32(tableName, "id")
	_tcVer4BanUserset.UID = field.NewInt32(tableName, "uid")
	_tcVer4BanUserset.C = field.NewString(tableName, "c")

	_tcVer4BanUserset.fillFieldMap()

	return _tcVer4BanUserset
}

type tcVer4BanUserset struct {
	tcVer4BanUsersetDo tcVer4BanUsersetDo

	ALL field.Asterisk
	ID  field.Int32
	UID field.Int32
	C   field.String

	fieldMap map[string]field.Expr
}

func (t tcVer4BanUserset) Table(newTableName string) *tcVer4BanUserset {
	t.tcVer4BanUsersetDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tcVer4BanUserset) As(alias string) *tcVer4BanUserset {
	t.tcVer4BanUsersetDo.DO = *(t.tcVer4BanUsersetDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tcVer4BanUserset) updateTableName(table string) *tcVer4BanUserset {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.UID = field.NewInt32(table, "uid")
	t.C = field.NewString(table, "c")

	t.fillFieldMap()

	return t
}

func (t *tcVer4BanUserset) WithContext(ctx context.Context) *tcVer4BanUsersetDo {
	return t.tcVer4BanUsersetDo.WithContext(ctx)
}

func (t tcVer4BanUserset) TableName() string { return t.tcVer4BanUsersetDo.TableName() }

func (t tcVer4BanUserset) Alias() string { return t.tcVer4BanUsersetDo.Alias() }

func (t tcVer4BanUserset) Columns(cols ...field.Expr) gen.Columns {
	return t.tcVer4BanUsersetDo.Columns(cols...)
}

func (t *tcVer4BanUserset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tcVer4BanUserset) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["id"] = t.ID
	t.fieldMap["uid"] = t.UID
	t.fieldMap["c"] = t.C
}

func (t tcVer4BanUserset) clone(db *gorm.DB) tcVer4BanUserset {
	t.tcVer4BanUsersetDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tcVer4BanUserset) replaceDB(db *gorm.DB) tcVer4BanUserset {
	t.tcVer4BanUsersetDo.ReplaceDB(db)
	return t
}

type tcVer4BanUsersetDo struct{ gen.DO }

func (t tcVer4BanUsersetDo) Debug() *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Debug())
}

func (t tcVer4BanUsersetDo) WithContext(ctx context.Context) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tcVer4BanUsersetDo) ReadDB() *tcVer4BanUsersetDo {
	return t.Clauses(dbresolver.Read)
}

func (t tcVer4BanUsersetDo) WriteDB() *tcVer4BanUsersetDo {
	return t.Clauses(dbresolver.Write)
}

func (t tcVer4BanUsersetDo) Session(config *gorm.Session) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Session(config))
}

func (t tcVer4BanUsersetDo) Clauses(conds ...clause.Expression) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tcVer4BanUsersetDo) Returning(value interface{}, columns ...string) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tcVer4BanUsersetDo) Not(conds ...gen.Condition) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tcVer4BanUsersetDo) Or(conds ...gen.Condition) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tcVer4BanUsersetDo) Select(conds ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tcVer4BanUsersetDo) Where(conds ...gen.Condition) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tcVer4BanUsersetDo) Order(conds ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tcVer4BanUsersetDo) Distinct(cols ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tcVer4BanUsersetDo) Omit(cols ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tcVer4BanUsersetDo) Join(table schema.Tabler, on ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tcVer4BanUsersetDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tcVer4BanUsersetDo) RightJoin(table schema.Tabler, on ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tcVer4BanUsersetDo) Group(cols ...field.Expr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tcVer4BanUsersetDo) Having(conds ...gen.Condition) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tcVer4BanUsersetDo) Limit(limit int) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tcVer4BanUsersetDo) Offset(offset int) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tcVer4BanUsersetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tcVer4BanUsersetDo) Unscoped() *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tcVer4BanUsersetDo) Create(values ...*model.TcVer4BanUserset) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tcVer4BanUsersetDo) CreateInBatches(values []*model.TcVer4BanUserset, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tcVer4BanUsersetDo) Save(values ...*model.TcVer4BanUserset) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tcVer4BanUsersetDo) First() (*model.TcVer4BanUserset, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanUserset), nil
	}
}

func (t tcVer4BanUsersetDo) Take() (*model.TcVer4BanUserset, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanUserset), nil
	}
}

func (t tcVer4BanUsersetDo) Last() (*model.TcVer4BanUserset, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanUserset), nil
	}
}

func (t tcVer4BanUsersetDo) Find() ([]*model.TcVer4BanUserset, error) {
	result, err := t.DO.Find()
	return result.([]*model.TcVer4BanUserset), err
}

func (t tcVer4BanUsersetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TcVer4BanUserset, err error) {
	buf := make([]*model.TcVer4BanUserset, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tcVer4BanUsersetDo) FindInBatches(result *[]*model.TcVer4BanUserset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tcVer4BanUsersetDo) Attrs(attrs ...field.AssignExpr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tcVer4BanUsersetDo) Assign(attrs ...field.AssignExpr) *tcVer4BanUsersetDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tcVer4BanUsersetDo) Joins(fields ...field.RelationField) *tcVer4BanUsersetDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tcVer4BanUsersetDo) Preload(fields ...field.RelationField) *tcVer4BanUsersetDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tcVer4BanUsersetDo) FirstOrInit() (*model.TcVer4BanUserset, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanUserset), nil
	}
}

func (t tcVer4BanUsersetDo) FirstOrCreate() (*model.TcVer4BanUserset, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanUserset), nil
	}
}

func (t tcVer4BanUsersetDo) FindByPage(offset int, limit int) (result []*model.TcVer4BanUserset, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tcVer4BanUsersetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tcVer4BanUsersetDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tcVer4BanUsersetDo) Delete(models ...*model.TcVer4BanUserset) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tcVer4BanUsersetDo) withDO(do gen.Dao) *tcVer4BanUsersetDo {
	t.DO = *do.(*gen.DO)
	return t
}
