// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/BANKA2017/tbsign_go/dao/model"
)

func newTcVer4BanList(db *gorm.DB, opts ...gen.DOOption) tcVer4BanList {
	_tcVer4BanList := tcVer4BanList{}

	_tcVer4BanList.tcVer4BanListDo.UseDB(db, opts...)
	_tcVer4BanList.tcVer4BanListDo.UseModel(&model.TcVer4BanList{})

	tableName := _tcVer4BanList.tcVer4BanListDo.TableName()
	_tcVer4BanList.ALL = field.NewAsterisk(tableName)
	_tcVer4BanList.ID = field.NewInt32(tableName, "id")
	_tcVer4BanList.UID = field.NewInt32(tableName, "uid")
	_tcVer4BanList.Pid = field.NewInt32(tableName, "pid")
	_tcVer4BanList.Name = field.NewString(tableName, "name")
	_tcVer4BanList.NameShow = field.NewString(tableName, "name_show")
	_tcVer4BanList.Portrait = field.NewString(tableName, "portrait")
	_tcVer4BanList.Tieba = field.NewString(tableName, "tieba")
	_tcVer4BanList.Stime = field.NewInt32(tableName, "stime")
	_tcVer4BanList.Etime = field.NewInt32(tableName, "etime")
	_tcVer4BanList.Log = field.NewString(tableName, "log")
	_tcVer4BanList.Date = field.NewInt32(tableName, "date")

	_tcVer4BanList.fillFieldMap()

	return _tcVer4BanList
}

type tcVer4BanList struct {
	tcVer4BanListDo tcVer4BanListDo

	ALL      field.Asterisk
	ID       field.Int32
	UID      field.Int32
	Pid      field.Int32
	Name     field.String
	NameShow field.String
	Portrait field.String
	Tieba    field.String
	Stime    field.Int32
	Etime    field.Int32
	Log      field.String
	Date     field.Int32

	fieldMap map[string]field.Expr
}

func (t tcVer4BanList) Table(newTableName string) *tcVer4BanList {
	t.tcVer4BanListDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tcVer4BanList) As(alias string) *tcVer4BanList {
	t.tcVer4BanListDo.DO = *(t.tcVer4BanListDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tcVer4BanList) updateTableName(table string) *tcVer4BanList {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.UID = field.NewInt32(table, "uid")
	t.Pid = field.NewInt32(table, "pid")
	t.Name = field.NewString(table, "name")
	t.NameShow = field.NewString(table, "name_show")
	t.Portrait = field.NewString(table, "portrait")
	t.Tieba = field.NewString(table, "tieba")
	t.Stime = field.NewInt32(table, "stime")
	t.Etime = field.NewInt32(table, "etime")
	t.Log = field.NewString(table, "log")
	t.Date = field.NewInt32(table, "date")

	t.fillFieldMap()

	return t
}

func (t *tcVer4BanList) WithContext(ctx context.Context) *tcVer4BanListDo {
	return t.tcVer4BanListDo.WithContext(ctx)
}

func (t tcVer4BanList) TableName() string { return t.tcVer4BanListDo.TableName() }

func (t tcVer4BanList) Alias() string { return t.tcVer4BanListDo.Alias() }

func (t tcVer4BanList) Columns(cols ...field.Expr) gen.Columns {
	return t.tcVer4BanListDo.Columns(cols...)
}

func (t *tcVer4BanList) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tcVer4BanList) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 11)
	t.fieldMap["id"] = t.ID
	t.fieldMap["uid"] = t.UID
	t.fieldMap["pid"] = t.Pid
	t.fieldMap["name"] = t.Name
	t.fieldMap["name_show"] = t.NameShow
	t.fieldMap["portrait"] = t.Portrait
	t.fieldMap["tieba"] = t.Tieba
	t.fieldMap["stime"] = t.Stime
	t.fieldMap["etime"] = t.Etime
	t.fieldMap["log"] = t.Log
	t.fieldMap["date"] = t.Date
}

func (t tcVer4BanList) clone(db *gorm.DB) tcVer4BanList {
	t.tcVer4BanListDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tcVer4BanList) replaceDB(db *gorm.DB) tcVer4BanList {
	t.tcVer4BanListDo.ReplaceDB(db)
	return t
}

type tcVer4BanListDo struct{ gen.DO }

func (t tcVer4BanListDo) Debug() *tcVer4BanListDo {
	return t.withDO(t.DO.Debug())
}

func (t tcVer4BanListDo) WithContext(ctx context.Context) *tcVer4BanListDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tcVer4BanListDo) ReadDB() *tcVer4BanListDo {
	return t.Clauses(dbresolver.Read)
}

func (t tcVer4BanListDo) WriteDB() *tcVer4BanListDo {
	return t.Clauses(dbresolver.Write)
}

func (t tcVer4BanListDo) Session(config *gorm.Session) *tcVer4BanListDo {
	return t.withDO(t.DO.Session(config))
}

func (t tcVer4BanListDo) Clauses(conds ...clause.Expression) *tcVer4BanListDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tcVer4BanListDo) Returning(value interface{}, columns ...string) *tcVer4BanListDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tcVer4BanListDo) Not(conds ...gen.Condition) *tcVer4BanListDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tcVer4BanListDo) Or(conds ...gen.Condition) *tcVer4BanListDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tcVer4BanListDo) Select(conds ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tcVer4BanListDo) Where(conds ...gen.Condition) *tcVer4BanListDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tcVer4BanListDo) Order(conds ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tcVer4BanListDo) Distinct(cols ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tcVer4BanListDo) Omit(cols ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tcVer4BanListDo) Join(table schema.Tabler, on ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tcVer4BanListDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tcVer4BanListDo) RightJoin(table schema.Tabler, on ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tcVer4BanListDo) Group(cols ...field.Expr) *tcVer4BanListDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tcVer4BanListDo) Having(conds ...gen.Condition) *tcVer4BanListDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tcVer4BanListDo) Limit(limit int) *tcVer4BanListDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tcVer4BanListDo) Offset(offset int) *tcVer4BanListDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tcVer4BanListDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tcVer4BanListDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tcVer4BanListDo) Unscoped() *tcVer4BanListDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tcVer4BanListDo) Create(values ...*model.TcVer4BanList) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tcVer4BanListDo) CreateInBatches(values []*model.TcVer4BanList, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tcVer4BanListDo) Save(values ...*model.TcVer4BanList) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tcVer4BanListDo) First() (*model.TcVer4BanList, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanList), nil
	}
}

func (t tcVer4BanListDo) Take() (*model.TcVer4BanList, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanList), nil
	}
}

func (t tcVer4BanListDo) Last() (*model.TcVer4BanList, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanList), nil
	}
}

func (t tcVer4BanListDo) Find() ([]*model.TcVer4BanList, error) {
	result, err := t.DO.Find()
	return result.([]*model.TcVer4BanList), err
}

func (t tcVer4BanListDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TcVer4BanList, err error) {
	buf := make([]*model.TcVer4BanList, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tcVer4BanListDo) FindInBatches(result *[]*model.TcVer4BanList, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tcVer4BanListDo) Attrs(attrs ...field.AssignExpr) *tcVer4BanListDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tcVer4BanListDo) Assign(attrs ...field.AssignExpr) *tcVer4BanListDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tcVer4BanListDo) Joins(fields ...field.RelationField) *tcVer4BanListDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tcVer4BanListDo) Preload(fields ...field.RelationField) *tcVer4BanListDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tcVer4BanListDo) FirstOrInit() (*model.TcVer4BanList, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanList), nil
	}
}

func (t tcVer4BanListDo) FirstOrCreate() (*model.TcVer4BanList, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TcVer4BanList), nil
	}
}

func (t tcVer4BanListDo) FindByPage(offset int, limit int) (result []*model.TcVer4BanList, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tcVer4BanListDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tcVer4BanListDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tcVer4BanListDo) Delete(models ...*model.TcVer4BanList) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tcVer4BanListDo) withDO(do gen.Dao) *tcVer4BanListDo {
	t.DO = *do.(*gen.DO)
	return t
}
