package assets

var DefaultOptions = map[string]string{
	"ann":                         "欢迎使用 TbSign➡️",
	"icp":                         "",
	"bduss_num":                   "0",
	"core_version":                "5.01",
	"cron_limit":                  "20",
	"cron_sign_again":             "a:2:{s:3:\"num\";i:0;s:6:\"lastdo\";s:10:\"2000-01-01\";}",
	"cktime":                      "864000",
	"enable_addtieba":             "1",
	"enable_reg":                  "1",
	"mail_auth":                   "0",
	"mail_host":                   "",
	"mail_mode":                   "SMTP",
	"mail_name":                   "",
	"mail_port":                   "25",
	"mail_secure":                 "tls",
	"mail_smtpname":               "",
	"mail_smtppw":                 "",
	"mail_yourname":               "no-reply",
	"retry_max":                   "20",
	"sign_asyn":                   "0",
	"sign_hour":                   "0",
	"sign_mode":                   "a:1:{i:0;s:1:\"1\";}",
	"sign_multith":                "0",
	"sign_sleep":                  "0",
	"stop_reg":                    "🈲 已关闭注册 (已废弃)",
	"system_description":          "TbSign➡️，用于完成贴吧签到和各种每日任务",
	"system_keywords":             "贴吧, 签到, 任务, 循环封禁, 名人堂, 成长任务, 自动刷新",
	"system_name":                 "TbSign➡️",
	"system_url":                  "",
	"tb_max":                      "0",
	"yr_reg":                      "",
	"go_ver":                      "0",
	"go_forum_sync_policy":        "add_only",
	"go_ntfy_addr":                "https://ntfy.sh",
	"go_bark_addr":                "https://api.day.app",
	"go_pushdeer_addr":            "https://api2.pushdeer.com",
	"go_export_personal_data":     "0",
	"go_import_personal_data":     "0",
	"go_encrypt":                  "0",
	"go_re_check_in_max_interval": "1",
	"go_daily_report_hour":        "-1",

	// should be edited in future versions
	"go_plugin_batch_tasks":              "0",
	"go_create_user_option_if_not_exist": "1",
	"go_next_upgrade_func":               "0",
	"go_allow_downgrade":                 "0",
	"go_wait_for_next_minute_on_startup": "0",
}
