// tbclient.GetBawuInfo.GetBawuInfoResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: GetBawuInfoResIdl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBawuInfoResIdl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *GetBawuInfoResIdl_DataRes `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error *Error                     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetBawuInfoResIdl) Reset() {
	*x = GetBawuInfoResIdl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetBawuInfoResIdl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBawuInfoResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl) ProtoMessage() {}

func (x *GetBawuInfoResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetBawuInfoResIdl) GetData() *GetBawuInfoResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBawuInfoResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetBawuInfoResIdl_DataRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BawuTeamInfo *GetBawuInfoResIdl_DataRes_BawuTeam `protobuf:"bytes,1,opt,name=bawu_team_info,json=bawuTeamInfo,proto3" json:"bawu_team_info,omitempty"`
}

func (x *GetBawuInfoResIdl_DataRes) Reset() {
	*x = GetBawuInfoResIdl_DataRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetBawuInfoResIdl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBawuInfoResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetBawuInfoResIdl_DataRes) GetBawuTeamInfo() *GetBawuInfoResIdl_DataRes_BawuTeam {
	if x != nil {
		return x.BawuTeamInfo
	}
	return nil
}

type GetBawuInfoResIdl_DataRes_BawuTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalNum     int32                                             `protobuf:"varint,1,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	BawuTeamList []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes `protobuf:"bytes,2,rep,name=bawu_team_list,json=bawuTeamList,proto3" json:"bawu_team_list,omitempty"`
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) Reset() {
	*x = GetBawuInfoResIdl_DataRes_BawuTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetBawuInfoResIdl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes_BawuTeam) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes_BawuTeam.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes_BawuTeam) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam) GetBawuTeamList() []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes {
	if x != nil {
		return x.BawuTeamList
	}
	return nil
}

type GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string                                                            `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleInfo []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub `protobuf:"bytes,2,rep,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) Reset() {
	*x = GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetBawuInfoResIdl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes) GetRoleInfo() []*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

type GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Portrait  string `protobuf:"bytes,5,opt,name=portrait,proto3" json:"portrait,omitempty"`
	UserLevel int32  `protobuf:"varint,6,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	UserName  string `protobuf:"bytes,8,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NameShow  string `protobuf:"bytes,9,opt,name=name_show,json=nameShow,proto3" json:"name_show,omitempty"`
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) Reset() {
	*x = GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetBawuInfoResIdl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) ProtoMessage() {}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) ProtoReflect() protoreflect.Message {
	mi := &file_GetBawuInfoResIdl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub.ProtoReflect.Descriptor instead.
func (*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) Descriptor() ([]byte, []int) {
	return file_GetBawuInfoResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetPortrait() string {
	if x != nil {
		return x.Portrait
	}
	return ""
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetUserLevel() int32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub) GetNameShow() string {
	if x != nil {
		return x.NameShow
	}
	return ""
}

var File_GetBawuInfoResIdl_proto protoreflect.FileDescriptor

var file_GetBawuInfoResIdl_proto_rawDesc = []byte{
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x61, 0x77, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x49, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe6, 0x04, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x77, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x12, 0x2e, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x77, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x82, 0x04, 0x0a, 0x07, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x0e, 0x62, 0x61, 0x77, 0x75, 0x5f, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x77, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x49,
	0x64, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x77, 0x75, 0x54,
	0x65, 0x61, 0x6d, 0x52, 0x0c, 0x62, 0x61, 0x77, 0x75, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0xab, 0x03, 0x0a, 0x08, 0x42, 0x61, 0x77, 0x75, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x55, 0x0a, 0x0e, 0x62,
	0x61, 0x77, 0x75, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x77, 0x75, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x2e,
	0x42, 0x61, 0x77, 0x75, 0x54, 0x65, 0x61, 0x6d, 0x2e, 0x42, 0x61, 0x77, 0x75, 0x52, 0x6f, 0x6c,
	0x65, 0x44, 0x65, 0x73, 0x52, 0x0c, 0x62, 0x61, 0x77, 0x75, 0x54, 0x65, 0x61, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x1a, 0xaa, 0x02, 0x0a, 0x0b, 0x42, 0x61, 0x77, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x44,
	0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x5c, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x77, 0x75, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x2e, 0x42,
	0x61, 0x77, 0x75, 0x54, 0x65, 0x61, 0x6d, 0x2e, 0x42, 0x61, 0x77, 0x75, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x77, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x75, 0x62, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x9f, 0x01,
	0x0a, 0x0f, 0x42, 0x61, 0x77, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x75,
	0x62, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f,
	0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f,
	0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetBawuInfoResIdl_proto_rawDescOnce sync.Once
	file_GetBawuInfoResIdl_proto_rawDescData = file_GetBawuInfoResIdl_proto_rawDesc
)

func file_GetBawuInfoResIdl_proto_rawDescGZIP() []byte {
	file_GetBawuInfoResIdl_proto_rawDescOnce.Do(func() {
		file_GetBawuInfoResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetBawuInfoResIdl_proto_rawDescData)
	})
	return file_GetBawuInfoResIdl_proto_rawDescData
}

var file_GetBawuInfoResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_GetBawuInfoResIdl_proto_goTypes = []interface{}{
	(*GetBawuInfoResIdl)(nil),                                              // 0: GetBawuInfoResIdl
	(*GetBawuInfoResIdl_DataRes)(nil),                                      // 1: GetBawuInfoResIdl.DataRes
	(*GetBawuInfoResIdl_DataRes_BawuTeam)(nil),                             // 2: GetBawuInfoResIdl.DataRes.BawuTeam
	(*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes)(nil),                 // 3: GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes
	(*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub)(nil), // 4: GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes.BawuRoleInfoPub
	(*Error)(nil), // 5: Error
}
var file_GetBawuInfoResIdl_proto_depIdxs = []int32{
	1, // 0: GetBawuInfoResIdl.data:type_name -> GetBawuInfoResIdl.DataRes
	5, // 1: GetBawuInfoResIdl.error:type_name -> Error
	2, // 2: GetBawuInfoResIdl.DataRes.bawu_team_info:type_name -> GetBawuInfoResIdl.DataRes.BawuTeam
	3, // 3: GetBawuInfoResIdl.DataRes.BawuTeam.bawu_team_list:type_name -> GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes
	4, // 4: GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes.role_info:type_name -> GetBawuInfoResIdl.DataRes.BawuTeam.BawuRoleDes.BawuRoleInfoPub
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_GetBawuInfoResIdl_proto_init() }
func file_GetBawuInfoResIdl_proto_init() {
	if File_GetBawuInfoResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetBawuInfoResIdl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBawuInfoResIdl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetBawuInfoResIdl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBawuInfoResIdl_DataRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetBawuInfoResIdl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBawuInfoResIdl_DataRes_BawuTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetBawuInfoResIdl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetBawuInfoResIdl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBawuInfoResIdl_DataRes_BawuTeam_BawuRoleDes_BawuRoleInfoPub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetBawuInfoResIdl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetBawuInfoResIdl_proto_goTypes,
		DependencyIndexes: file_GetBawuInfoResIdl_proto_depIdxs,
		MessageInfos:      file_GetBawuInfoResIdl_proto_msgTypes,
	}.Build()
	File_GetBawuInfoResIdl_proto = out.File
	file_GetBawuInfoResIdl_proto_rawDesc = nil
	file_GetBawuInfoResIdl_proto_goTypes = nil
	file_GetBawuInfoResIdl_proto_depIdxs = nil
}
