// tbclient.GetForumDetail.GetForumDetailResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: GetForumDetailResIdl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetForumDetailResIdl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error                        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *GetForumDetailResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetForumDetailResIdl) Reset() {
	*x = GetForumDetailResIdl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetForumDetailResIdl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetForumDetailResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumDetailResIdl) ProtoMessage() {}

func (x *GetForumDetailResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumDetailResIdl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumDetailResIdl.ProtoReflect.Descriptor instead.
func (*GetForumDetailResIdl) Descriptor() ([]byte, []int) {
	return file_GetForumDetailResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetForumDetailResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetForumDetailResIdl) GetData() *GetForumDetailResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetForumDetailResIdl_DataRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForumInfo   *GetForumDetailResIdl_DataRes_RecommendForumInfo `protobuf:"bytes,1,opt,name=forum_info,json=forumInfo,proto3" json:"forum_info,omitempty"`
	ElectionTab *GetForumDetailResIdl_DataRes_ManagerElectionTab `protobuf:"bytes,8,opt,name=election_tab,json=electionTab,proto3" json:"election_tab,omitempty"`
}

func (x *GetForumDetailResIdl_DataRes) Reset() {
	*x = GetForumDetailResIdl_DataRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetForumDetailResIdl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetForumDetailResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumDetailResIdl_DataRes) ProtoMessage() {}

func (x *GetForumDetailResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumDetailResIdl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumDetailResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetForumDetailResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetForumDetailResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetForumDetailResIdl_DataRes) GetForumInfo() *GetForumDetailResIdl_DataRes_RecommendForumInfo {
	if x != nil {
		return x.ForumInfo
	}
	return nil
}

func (x *GetForumDetailResIdl_DataRes) GetElectionTab() *GetForumDetailResIdl_DataRes_ManagerElectionTab {
	if x != nil {
		return x.ElectionTab
	}
	return nil
}

type GetForumDetailResIdl_DataRes_RecommendForumInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar       string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ForumId      uint64 `protobuf:"varint,2,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	ForumName    string `protobuf:"bytes,3,opt,name=forum_name,json=forumName,proto3" json:"forum_name,omitempty"`
	MemberCount  uint32 `protobuf:"varint,5,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	ThreadCount  uint32 `protobuf:"varint,6,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	Slogan       string `protobuf:"bytes,7,opt,name=slogan,proto3" json:"slogan,omitempty"`
	Lv1Name      string `protobuf:"bytes,18,opt,name=lv1_name,json=lv1Name,proto3" json:"lv1_name,omitempty"`
	AvatarOrigin string `protobuf:"bytes,20,opt,name=avatar_origin,json=avatarOrigin,proto3" json:"avatar_origin,omitempty"`
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) Reset() {
	*x = GetForumDetailResIdl_DataRes_RecommendForumInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetForumDetailResIdl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumDetailResIdl_DataRes_RecommendForumInfo) ProtoMessage() {}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumDetailResIdl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumDetailResIdl_DataRes_RecommendForumInfo.ProtoReflect.Descriptor instead.
func (*GetForumDetailResIdl_DataRes_RecommendForumInfo) Descriptor() ([]byte, []int) {
	return file_GetForumDetailResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetForumId() uint64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetForumName() string {
	if x != nil {
		return x.ForumName
	}
	return ""
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetMemberCount() uint32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetThreadCount() uint32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetSlogan() string {
	if x != nil {
		return x.Slogan
	}
	return ""
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetLv1Name() string {
	if x != nil {
		return x.Lv1Name
	}
	return ""
}

func (x *GetForumDetailResIdl_DataRes_RecommendForumInfo) GetAvatarOrigin() string {
	if x != nil {
		return x.AvatarOrigin
	}
	return ""
}

type GetForumDetailResIdl_DataRes_ManagerElectionTab struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewStrategyText string `protobuf:"bytes,5,opt,name=new_strategy_text,json=newStrategyText,proto3" json:"new_strategy_text,omitempty"`
}

func (x *GetForumDetailResIdl_DataRes_ManagerElectionTab) Reset() {
	*x = GetForumDetailResIdl_DataRes_ManagerElectionTab{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetForumDetailResIdl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetForumDetailResIdl_DataRes_ManagerElectionTab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumDetailResIdl_DataRes_ManagerElectionTab) ProtoMessage() {}

func (x *GetForumDetailResIdl_DataRes_ManagerElectionTab) ProtoReflect() protoreflect.Message {
	mi := &file_GetForumDetailResIdl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumDetailResIdl_DataRes_ManagerElectionTab.ProtoReflect.Descriptor instead.
func (*GetForumDetailResIdl_DataRes_ManagerElectionTab) Descriptor() ([]byte, []int) {
	return file_GetForumDetailResIdl_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *GetForumDetailResIdl_DataRes_ManagerElectionTab) GetNewStrategyText() string {
	if x != nil {
		return x.NewStrategyText
	}
	return ""
}

var File_GetForumDetailResIdl_proto protoreflect.FileDescriptor

var file_GetForumDetailResIdl_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x04, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x49,
	0x64, 0x6c, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0xf8, 0x03, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12,
	0x4f, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x75,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x53, 0x0a, 0x0c, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x62,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x75,
	0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x45, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x62, 0x52, 0x0b, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x61, 0x62, 0x1a, 0x84, 0x02, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x67, 0x61, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x67, 0x61, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x76, 0x31, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x76, 0x31, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x1a, 0x40, 0x0a, 0x12,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x61, 0x62, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e,
	0x65, 0x77, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x54, 0x65, 0x78, 0x74, 0x42, 0x03,
	0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetForumDetailResIdl_proto_rawDescOnce sync.Once
	file_GetForumDetailResIdl_proto_rawDescData = file_GetForumDetailResIdl_proto_rawDesc
)

func file_GetForumDetailResIdl_proto_rawDescGZIP() []byte {
	file_GetForumDetailResIdl_proto_rawDescOnce.Do(func() {
		file_GetForumDetailResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetForumDetailResIdl_proto_rawDescData)
	})
	return file_GetForumDetailResIdl_proto_rawDescData
}

var file_GetForumDetailResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GetForumDetailResIdl_proto_goTypes = []interface{}{
	(*GetForumDetailResIdl)(nil),                            // 0: GetForumDetailResIdl
	(*GetForumDetailResIdl_DataRes)(nil),                    // 1: GetForumDetailResIdl.DataRes
	(*GetForumDetailResIdl_DataRes_RecommendForumInfo)(nil), // 2: GetForumDetailResIdl.DataRes.RecommendForumInfo
	(*GetForumDetailResIdl_DataRes_ManagerElectionTab)(nil), // 3: GetForumDetailResIdl.DataRes.ManagerElectionTab
	(*Error)(nil), // 4: Error
}
var file_GetForumDetailResIdl_proto_depIdxs = []int32{
	4, // 0: GetForumDetailResIdl.error:type_name -> Error
	1, // 1: GetForumDetailResIdl.data:type_name -> GetForumDetailResIdl.DataRes
	2, // 2: GetForumDetailResIdl.DataRes.forum_info:type_name -> GetForumDetailResIdl.DataRes.RecommendForumInfo
	3, // 3: GetForumDetailResIdl.DataRes.election_tab:type_name -> GetForumDetailResIdl.DataRes.ManagerElectionTab
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_GetForumDetailResIdl_proto_init() }
func file_GetForumDetailResIdl_proto_init() {
	if File_GetForumDetailResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetForumDetailResIdl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetForumDetailResIdl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetForumDetailResIdl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetForumDetailResIdl_DataRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetForumDetailResIdl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetForumDetailResIdl_DataRes_RecommendForumInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetForumDetailResIdl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetForumDetailResIdl_DataRes_ManagerElectionTab); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetForumDetailResIdl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetForumDetailResIdl_proto_goTypes,
		DependencyIndexes: file_GetForumDetailResIdl_proto_depIdxs,
		MessageInfos:      file_GetForumDetailResIdl_proto_msgTypes,
	}.Build()
	File_GetForumDetailResIdl_proto = out.File
	file_GetForumDetailResIdl_proto_rawDesc = nil
	file_GetForumDetailResIdl_proto_goTypes = nil
	file_GetForumDetailResIdl_proto_depIdxs = nil
}
