// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: GetPrivateInfoResIdl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPrivateInfoResIdl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *GetPrivateInfoResIdl_ResData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error *Error                        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetPrivateInfoResIdl) Reset() {
	*x = GetPrivateInfoResIdl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetPrivateInfoResIdl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrivateInfoResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateInfoResIdl) ProtoMessage() {}

func (x *GetPrivateInfoResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetPrivateInfoResIdl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateInfoResIdl.ProtoReflect.Descriptor instead.
func (*GetPrivateInfoResIdl) Descriptor() ([]byte, []int) {
	return file_GetPrivateInfoResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetPrivateInfoResIdl) GetData() *GetPrivateInfoResIdl_ResData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetPrivateInfoResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPrivateInfoResIdl_ResData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location         int32       `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
	Post             int32       `protobuf:"varint,2,opt,name=post,proto3" json:"post,omitempty"`
	Like             int32       `protobuf:"varint,3,opt,name=like,proto3" json:"like,omitempty"`
	Group            int32       `protobuf:"varint,4,opt,name=group,proto3" json:"group,omitempty"`
	User             *SimpleUser `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Live             int32       `protobuf:"varint,6,opt,name=live,proto3" json:"live,omitempty"`
	ForumNum         int32       `protobuf:"varint,7,opt,name=forum_num,json=forumNum,proto3" json:"forum_num,omitempty"`
	Reply            int32       `protobuf:"varint,8,opt,name=reply,proto3" json:"reply,omitempty"`
	BazhuShowInside  int32       `protobuf:"varint,9,opt,name=bazhu_show_inside,json=bazhuShowInside,proto3" json:"bazhu_show_inside,omitempty"`
	BazhuShowOutside int32       `protobuf:"varint,10,opt,name=bazhu_show_outside,json=bazhuShowOutside,proto3" json:"bazhu_show_outside,omitempty"`
	Follow           int32       `protobuf:"varint,11,opt,name=follow,proto3" json:"follow,omitempty"`
}

func (x *GetPrivateInfoResIdl_ResData) Reset() {
	*x = GetPrivateInfoResIdl_ResData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetPrivateInfoResIdl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrivateInfoResIdl_ResData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateInfoResIdl_ResData) ProtoMessage() {}

func (x *GetPrivateInfoResIdl_ResData) ProtoReflect() protoreflect.Message {
	mi := &file_GetPrivateInfoResIdl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateInfoResIdl_ResData.ProtoReflect.Descriptor instead.
func (*GetPrivateInfoResIdl_ResData) Descriptor() ([]byte, []int) {
	return file_GetPrivateInfoResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetPrivateInfoResIdl_ResData) GetLocation() int32 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetPost() int32 {
	if x != nil {
		return x.Post
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetUser() *SimpleUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetPrivateInfoResIdl_ResData) GetLive() int32 {
	if x != nil {
		return x.Live
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetForumNum() int32 {
	if x != nil {
		return x.ForumNum
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetReply() int32 {
	if x != nil {
		return x.Reply
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetBazhuShowInside() int32 {
	if x != nil {
		return x.BazhuShowInside
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetBazhuShowOutside() int32 {
	if x != nil {
		return x.BazhuShowOutside
	}
	return 0
}

func (x *GetPrivateInfoResIdl_ResData) GetFollow() int32 {
	if x != nil {
		return x.Follow
	}
	return 0
}

var File_GetPrivateInfoResIdl_proto protoreflect.FileDescriptor

var file_GetPrivateInfoResIdl_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x03, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x49, 0x64, 0x6c, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0xbd, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1f, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x76, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x61, 0x7a, 0x68, 0x75, 0x5f, 0x73, 0x68, 0x6f,
	0x77, 0x5f, 0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x62, 0x61, 0x7a, 0x68, 0x75, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x62, 0x61, 0x7a, 0x68, 0x75, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6f, 0x75,
	0x74, 0x73, 0x69, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x62, 0x61, 0x7a,
	0x68, 0x75, 0x53, 0x68, 0x6f, 0x77, 0x4f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_GetPrivateInfoResIdl_proto_rawDescOnce sync.Once
	file_GetPrivateInfoResIdl_proto_rawDescData = file_GetPrivateInfoResIdl_proto_rawDesc
)

func file_GetPrivateInfoResIdl_proto_rawDescGZIP() []byte {
	file_GetPrivateInfoResIdl_proto_rawDescOnce.Do(func() {
		file_GetPrivateInfoResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetPrivateInfoResIdl_proto_rawDescData)
	})
	return file_GetPrivateInfoResIdl_proto_rawDescData
}

var file_GetPrivateInfoResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetPrivateInfoResIdl_proto_goTypes = []interface{}{
	(*GetPrivateInfoResIdl)(nil),         // 0: GetPrivateInfoResIdl
	(*GetPrivateInfoResIdl_ResData)(nil), // 1: GetPrivateInfoResIdl.ResData
	(*Error)(nil),                        // 2: Error
	(*SimpleUser)(nil),                   // 3: SimpleUser
}
var file_GetPrivateInfoResIdl_proto_depIdxs = []int32{
	1, // 0: GetPrivateInfoResIdl.data:type_name -> GetPrivateInfoResIdl.ResData
	2, // 1: GetPrivateInfoResIdl.error:type_name -> Error
	3, // 2: GetPrivateInfoResIdl.ResData.user:type_name -> SimpleUser
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetPrivateInfoResIdl_proto_init() }
func file_GetPrivateInfoResIdl_proto_init() {
	if File_GetPrivateInfoResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_SimpleUser_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetPrivateInfoResIdl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrivateInfoResIdl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetPrivateInfoResIdl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrivateInfoResIdl_ResData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetPrivateInfoResIdl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetPrivateInfoResIdl_proto_goTypes,
		DependencyIndexes: file_GetPrivateInfoResIdl_proto_depIdxs,
		MessageInfos:      file_GetPrivateInfoResIdl_proto_msgTypes,
	}.Build()
	File_GetPrivateInfoResIdl_proto = out.File
	file_GetPrivateInfoResIdl_proto_rawDesc = nil
	file_GetPrivateInfoResIdl_proto_goTypes = nil
	file_GetPrivateInfoResIdl_proto_depIdxs = nil
}
