// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: GetPrivateInfoReqIdl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPrivateInfoReqIdl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *GetPrivateInfoReqIdl_ReqData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetPrivateInfoReqIdl) Reset() {
	*x = GetPrivateInfoReqIdl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetPrivateInfoReqIdl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrivateInfoReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateInfoReqIdl) ProtoMessage() {}

func (x *GetPrivateInfoReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetPrivateInfoReqIdl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateInfoReqIdl.ProtoReflect.Descriptor instead.
func (*GetPrivateInfoReqIdl) Descriptor() ([]byte, []int) {
	return file_GetPrivateInfoReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetPrivateInfoReqIdl) GetData() *GetPrivateInfoReqIdl_ReqData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPrivateInfoReqIdl_ReqData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Common *CommonReq `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *GetPrivateInfoReqIdl_ReqData) Reset() {
	*x = GetPrivateInfoReqIdl_ReqData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetPrivateInfoReqIdl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrivateInfoReqIdl_ReqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateInfoReqIdl_ReqData) ProtoMessage() {}

func (x *GetPrivateInfoReqIdl_ReqData) ProtoReflect() protoreflect.Message {
	mi := &file_GetPrivateInfoReqIdl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateInfoReqIdl_ReqData.ProtoReflect.Descriptor instead.
func (*GetPrivateInfoReqIdl_ReqData) Descriptor() ([]byte, []int) {
	return file_GetPrivateInfoReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetPrivateInfoReqIdl_ReqData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPrivateInfoReqIdl_ReqData) GetCommon() *CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

var File_GetPrivateInfoReqIdl_proto protoreflect.FileDescriptor

var file_GetPrivateInfoReqIdl_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x49, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x49, 0x64, 0x6c, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x49, 0x64, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x46, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetPrivateInfoReqIdl_proto_rawDescOnce sync.Once
	file_GetPrivateInfoReqIdl_proto_rawDescData = file_GetPrivateInfoReqIdl_proto_rawDesc
)

func file_GetPrivateInfoReqIdl_proto_rawDescGZIP() []byte {
	file_GetPrivateInfoReqIdl_proto_rawDescOnce.Do(func() {
		file_GetPrivateInfoReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetPrivateInfoReqIdl_proto_rawDescData)
	})
	return file_GetPrivateInfoReqIdl_proto_rawDescData
}

var file_GetPrivateInfoReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetPrivateInfoReqIdl_proto_goTypes = []interface{}{
	(*GetPrivateInfoReqIdl)(nil),         // 0: GetPrivateInfoReqIdl
	(*GetPrivateInfoReqIdl_ReqData)(nil), // 1: GetPrivateInfoReqIdl.ReqData
	(*CommonReq)(nil),                    // 2: CommonReq
}
var file_GetPrivateInfoReqIdl_proto_depIdxs = []int32{
	1, // 0: GetPrivateInfoReqIdl.data:type_name -> GetPrivateInfoReqIdl.ReqData
	2, // 1: GetPrivateInfoReqIdl.ReqData.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetPrivateInfoReqIdl_proto_init() }
func file_GetPrivateInfoReqIdl_proto_init() {
	if File_GetPrivateInfoReqIdl_proto != nil {
		return
	}
	file_CommonReq_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetPrivateInfoReqIdl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrivateInfoReqIdl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetPrivateInfoReqIdl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrivateInfoReqIdl_ReqData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetPrivateInfoReqIdl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetPrivateInfoReqIdl_proto_goTypes,
		DependencyIndexes: file_GetPrivateInfoReqIdl_proto_depIdxs,
		MessageInfos:      file_GetPrivateInfoReqIdl_proto_msgTypes,
	}.Build()
	File_GetPrivateInfoReqIdl_proto = out.File
	file_GetPrivateInfoReqIdl_proto_rawDesc = nil
	file_GetPrivateInfoReqIdl_proto_goTypes = nil
	file_GetPrivateInfoReqIdl_proto_depIdxs = nil
}
