// tbclient.GetUserByTiebaUid.GetUserByTiebaUidResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: GetUserByTiebaUidResIdl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByTiebaUidResIdl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error                           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *GetUserByTiebaUidResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserByTiebaUidResIdl) Reset() {
	*x = GetUserByTiebaUidResIdl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByTiebaUidResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTiebaUidResIdl) ProtoMessage() {}

func (x *GetUserByTiebaUidResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTiebaUidResIdl.ProtoReflect.Descriptor instead.
func (*GetUserByTiebaUidResIdl) Descriptor() ([]byte, []int) {
	return file_GetUserByTiebaUidResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByTiebaUidResIdl) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetUserByTiebaUidResIdl) GetData() *GetUserByTiebaUidResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserByTiebaUidResIdl_DataRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserByTiebaUidResIdl_DataRes) Reset() {
	*x = GetUserByTiebaUidResIdl_DataRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByTiebaUidResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTiebaUidResIdl_DataRes) ProtoMessage() {}

func (x *GetUserByTiebaUidResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserByTiebaUidResIdl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTiebaUidResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetUserByTiebaUidResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetUserByTiebaUidResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUserByTiebaUidResIdl_DataRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_GetUserByTiebaUidResIdl_proto protoreflect.FileDescriptor

var file_GetUserByTiebaUidResIdl_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x54, 0x69, 0x65, 0x62, 0x61,
	0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x55, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x54, 0x69, 0x65, 0x62, 0x61, 0x55, 0x69, 0x64, 0x52, 0x65,
	0x73, 0x49, 0x64, 0x6c, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x54, 0x69, 0x65, 0x62,
	0x61, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x49, 0x64, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x24, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetUserByTiebaUidResIdl_proto_rawDescOnce sync.Once
	file_GetUserByTiebaUidResIdl_proto_rawDescData = file_GetUserByTiebaUidResIdl_proto_rawDesc
)

func file_GetUserByTiebaUidResIdl_proto_rawDescGZIP() []byte {
	file_GetUserByTiebaUidResIdl_proto_rawDescOnce.Do(func() {
		file_GetUserByTiebaUidResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetUserByTiebaUidResIdl_proto_rawDescData)
	})
	return file_GetUserByTiebaUidResIdl_proto_rawDescData
}

var file_GetUserByTiebaUidResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetUserByTiebaUidResIdl_proto_goTypes = []interface{}{
	(*GetUserByTiebaUidResIdl)(nil),         // 0: GetUserByTiebaUidResIdl
	(*GetUserByTiebaUidResIdl_DataRes)(nil), // 1: GetUserByTiebaUidResIdl.DataRes
	(*Error)(nil),                           // 2: Error
	(*User)(nil),                            // 3: User
}
var file_GetUserByTiebaUidResIdl_proto_depIdxs = []int32{
	2, // 0: GetUserByTiebaUidResIdl.error:type_name -> Error
	1, // 1: GetUserByTiebaUidResIdl.data:type_name -> GetUserByTiebaUidResIdl.DataRes
	3, // 2: GetUserByTiebaUidResIdl.DataRes.user:type_name -> User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetUserByTiebaUidResIdl_proto_init() }
func file_GetUserByTiebaUidResIdl_proto_init() {
	if File_GetUserByTiebaUidResIdl_proto != nil {
		return
	}
	file_Error_proto_init()
	file_User_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetUserByTiebaUidResIdl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByTiebaUidResIdl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetUserByTiebaUidResIdl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByTiebaUidResIdl_DataRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetUserByTiebaUidResIdl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetUserByTiebaUidResIdl_proto_goTypes,
		DependencyIndexes: file_GetUserByTiebaUidResIdl_proto_depIdxs,
		MessageInfos:      file_GetUserByTiebaUidResIdl_proto_msgTypes,
	}.Build()
	File_GetUserByTiebaUidResIdl_proto = out.File
	file_GetUserByTiebaUidResIdl_proto_rawDesc = nil
	file_GetUserByTiebaUidResIdl_proto_goTypes = nil
	file_GetUserByTiebaUidResIdl_proto_depIdxs = nil
}
