// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: SimpleUser.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserStatus     int32  `protobuf:"varint,2,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	Secureemail    string `protobuf:"bytes,3,opt,name=secureemail,proto3" json:"secureemail,omitempty"`
	Securemobil    string `protobuf:"bytes,4,opt,name=securemobil,proto3" json:"securemobil,omitempty"`
	UserName       string `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserNickname   string `protobuf:"bytes,6,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	IncompleteUser uint32 `protobuf:"varint,7,opt,name=incomplete_user,json=incompleteUser,proto3" json:"incomplete_user,omitempty"`
	Portrait       string `protobuf:"bytes,8,opt,name=portrait,proto3" json:"portrait,omitempty"`
	AgreeType      int32  `protobuf:"varint,9,opt,name=agree_type,json=agreeType,proto3" json:"agree_type,omitempty"`
	AheadUrl       string `protobuf:"bytes,10,opt,name=ahead_url,json=aheadUrl,proto3" json:"ahead_url,omitempty"`
	BlockMsg       string `protobuf:"bytes,11,opt,name=block_msg,json=blockMsg,proto3" json:"block_msg,omitempty"`
	ShowOnlyme     int32  `protobuf:"varint,12,opt,name=show_onlyme,json=showOnlyme,proto3" json:"show_onlyme,omitempty"`
}

func (x *SimpleUser) Reset() {
	*x = SimpleUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SimpleUser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUser) ProtoMessage() {}

func (x *SimpleUser) ProtoReflect() protoreflect.Message {
	mi := &file_SimpleUser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUser.ProtoReflect.Descriptor instead.
func (*SimpleUser) Descriptor() ([]byte, []int) {
	return file_SimpleUser_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SimpleUser) GetUserStatus() int32 {
	if x != nil {
		return x.UserStatus
	}
	return 0
}

func (x *SimpleUser) GetSecureemail() string {
	if x != nil {
		return x.Secureemail
	}
	return ""
}

func (x *SimpleUser) GetSecuremobil() string {
	if x != nil {
		return x.Securemobil
	}
	return ""
}

func (x *SimpleUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SimpleUser) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *SimpleUser) GetIncompleteUser() uint32 {
	if x != nil {
		return x.IncompleteUser
	}
	return 0
}

func (x *SimpleUser) GetPortrait() string {
	if x != nil {
		return x.Portrait
	}
	return ""
}

func (x *SimpleUser) GetAgreeType() int32 {
	if x != nil {
		return x.AgreeType
	}
	return 0
}

func (x *SimpleUser) GetAheadUrl() string {
	if x != nil {
		return x.AheadUrl
	}
	return ""
}

func (x *SimpleUser) GetBlockMsg() string {
	if x != nil {
		return x.BlockMsg
	}
	return ""
}

func (x *SimpleUser) GetShowOnlyme() int32 {
	if x != nil {
		return x.ShowOnlyme
	}
	return 0
}

var File_SimpleUser_proto protoreflect.FileDescriptor

var file_SimpleUser_proto_rawDesc = []byte{
	0x0a, 0x10, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x8b, 0x03, 0x0a, 0x0a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x69, 0x6e, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f,
	0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f,
	0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x67, 0x72, 0x65, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x67, 0x72, 0x65,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x68, 0x65, 0x61, 0x64, 0x55,
	0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x6d, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x77, 0x4f, 0x6e, 0x6c, 0x79, 0x6d, 0x65,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SimpleUser_proto_rawDescOnce sync.Once
	file_SimpleUser_proto_rawDescData = file_SimpleUser_proto_rawDesc
)

func file_SimpleUser_proto_rawDescGZIP() []byte {
	file_SimpleUser_proto_rawDescOnce.Do(func() {
		file_SimpleUser_proto_rawDescData = protoimpl.X.CompressGZIP(file_SimpleUser_proto_rawDescData)
	})
	return file_SimpleUser_proto_rawDescData
}

var file_SimpleUser_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SimpleUser_proto_goTypes = []interface{}{
	(*SimpleUser)(nil), // 0: SimpleUser
}
var file_SimpleUser_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SimpleUser_proto_init() }
func file_SimpleUser_proto_init() {
	if File_SimpleUser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SimpleUser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SimpleUser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SimpleUser_proto_goTypes,
		DependencyIndexes: file_SimpleUser_proto_depIdxs,
		MessageInfos:      file_SimpleUser_proto_msgTypes,
	}.Build()
	File_SimpleUser_proto = out.File
	file_SimpleUser_proto_rawDesc = nil
	file_SimpleUser_proto_goTypes = nil
	file_SimpleUser_proto_depIdxs = nil
}
