// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcCron = "tc_cron"

// TcCron mapped from table <tc_cron>
type TcCron struct {
	Name   string `gorm:"column:name;primaryKey" json:"name"`
	Orde   int32  `gorm:"column:orde;not null" json:"orde"`
	File   string `gorm:"column:file;not null" json:"file"`
	No     int32  `gorm:"column:no;not null" json:"no"`
	Desc   string `gorm:"column:desc" json:"desc"`
	Freq   int32  `gorm:"column:freq;not null" json:"freq"`
	Lastdo int32  `gorm:"column:lastdo;not null" json:"lastdo"`
	Log    string `gorm:"column:log" json:"log"`
}

// TableName TcCron's table name
func (*TcCron) TableName() string {
	return TableNameTcCron
}
