// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcPlugin = "tc_plugins"

// TcPlugin mapped from table <tc_plugins>
type TcPlugin struct {
	Name    string `gorm:"column:name;primaryKey" json:"name"`
	Status  bool   `gorm:"column:status;not null" json:"status"`
	Ver     string `gorm:"column:ver;not null" json:"ver"`
	Options string `gorm:"column:options" json:"options"`
	Order   int32  `gorm:"column:order;not null" json:"order"`
}

// TableName TcPlugin's table name
func (*TcPlugin) TableName() string {
	return TableNameTcPlugin
}
