// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcUser = "tc_users"

// TcUser mapped from table <tc_users>
type TcUser struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Pw    string `gorm:"column:pw;not null" json:"pw"`
	Email string `gorm:"column:email;not null" json:"email"`
	Role  string `gorm:"column:role;not null;default:'user'" json:"role"`
	T     string `gorm:"column:t;not null;default:'tieba'" json:"t"`
}

// TableName TcUser's table name
func (*TcUser) TableName() string {
	return TableNameTcUser
}
