// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcUsersOption = "tc_users_options"

// TcUsersOption mapped from table <tc_users_options>
type TcUsersOption struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID   int32  `gorm:"column:uid;not null" json:"uid"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Value string `gorm:"column:value;not null" json:"value"`
}

// TableName TcUsersOption's table name
func (*TcUsersOption) TableName() string {
	return TableNameTcUsersOption
}
