// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcVer4RankLog = "tc_ver4_rank_log"

// TcVer4RankLog mapped from table <tc_ver4_rank_log>
type TcVer4RankLog struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID   int32  `gorm:"column:uid;not null" json:"uid"`
	Pid   int32  `gorm:"column:pid;not null" json:"pid"`
	Fid   int32  `gorm:"column:fid;not null" json:"fid"`
	Nid   string `gorm:"column:nid;not null" json:"nid"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Tieba string `gorm:"column:tieba;not null" json:"tieba"`
	Log   string `gorm:"column:log" json:"log"`
	Date  int32  `gorm:"column:date;not null" json:"date"`
}

// TableName TcVer4RankLog's table name
func (*TcVer4RankLog) TableName() string {
	return TableNameTcVer4RankLog
}
