// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcVer4BanList = "tc_ver4_ban_list"

// TcVer4BanList mapped from table <tc_ver4_ban_list>
type TcVer4BanList struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID      int32  `gorm:"column:uid;not null" json:"uid"`
	Pid      int32  `gorm:"column:pid;not null" json:"pid"`
	Name     string `gorm:"column:name" json:"name"`
	NameShow string `gorm:"column:name_show" json:"name_show"`
	Portrait string `gorm:"column:portrait" json:"portrait"`
	Tieba    string `gorm:"column:tieba;not null" json:"tieba"`
	Stime    int32  `gorm:"column:stime;not null" json:"stime"`
	Etime    int32  `gorm:"column:etime;not null" json:"etime"`
	Log      string `gorm:"column:log" json:"log"`
	Date     int32  `gorm:"column:date;not null" json:"date"`
}

// TableName TcVer4BanList's table name
func (*TcVer4BanList) TableName() string {
	return TableNameTcVer4BanList
}
