// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcVer4RankList = "tc_ver4_rank_list"

// TcVer4RankList mapped from table <tc_ver4_rank_list>
type TcVer4RankList struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Fid   int32  `gorm:"column:fid;not null" json:"fid"`
	Nid   string `gorm:"column:nid;not null" json:"nid"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Tieba string `gorm:"column:tieba;not null" json:"tieba"`
	Date  int32  `gorm:"column:date;not null" json:"date"`
}

// TableName TcVer4RankList's table name
func (*TcVer4RankList) TableName() string {
	return TableNameTcVer4RankList
}
